"""empty message

Revision ID: 1134a81b19aa
Revises: 96fc6b80cf73
Create Date: 2022-06-26 12:16:27.845183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1134a81b19aa'
down_revision = '96fc6b80cf73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elections', sa.Column('end_at', sa.DateTime(), nullable=True))
    op.drop_column('elections', 'is_working')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elections', sa.Column('is_working', sa.BOOLEAN(), nullable=True))
    op.drop_column('elections', 'end_at')
    # ### end Alembic commands ###
